# -*- mode: GNUmakefile -*-

# Where the files will be copied.  Note that for this to work you need an account with the School of Computer Science at the University of Birmingham, and an alias for the server defined in ~/.ssh/config
DEST = gromit:/bham/htdocs/website/research/projects/formare/code/auction-theory$(shell thisdir=$$PWD; cd $(PREFIX); basedir=$$PWD; echo $${thisdir\#$$basedir})
WWW_FILES = index.php \
	sidebar.php
LICENSE_FILES = README LICENSE LICENSE-CC-BY LICENSE-ISC
ZIP_FILE = $(shell basename $$PWD).zip
